#ifndef ENUMS_H
#define ENUMS_H

enum CharTokens{
			START,					LETTER,		  			DIGIT, 				UNDERSCORE,
			DOT,					ZERO,					WHITESPACE,			STOP,
			NEWLINE,				COMMA,					ASTERICK,			COLON,
			OPENBRACKETS,			CLOSEBRACKETS,			OPENPAREN,			CLOSEPAREN,
			OPENCURLY,				CLOSECURLY,				ERROR,				UNDEFINED_TOKEN,
			END,					UNDEFINED,				DASH,				AT, 
			EQUAL,					NOT,					GREATER_THAN,		LESS_THAN,
			PLUS,					MINUS,					RESET,				TAB,
			NULL_Token,				PERCENT,				QUOTES,				HASH_TAG,
			SINGLE_QUOTE,			DOUBLE_QUOTE,			FORWARD_SLASH,		BACK_SLASH,
			SEMI_COLON,				ESCLAMATION,
};

enum ReservedWords{
			ABSOLUTE,			RELATIVE,					MACRO,				MICRO,					REGISTERS,
			BEGIN,  			ARCH,  						X86_NUMBER, 		MICROS,					MACROS,
			OPERATORS,			UNKNOWN_KEYWORD,			X86_3,				X86_2,					ARM,			
			MIPS,				END_LIT,					OPEN_COMMENTS,  	CLOSE_COMMENTS,			INLINE_COMMENTS,
			OPTIONS,			VALUES,						
};

enum JsonReserved{
			STARTESCLAMATIONCURLY = 100,							ENDESCLAMATIONCURLY = 101,		ABSOLUTE_KEY = 102,
			RELATIVE_KEY = 103,										LABEL = 104, 					ID = 105,
			REG_1 = 106,											REG_2 = 107,					REG_3 = 108,
};




enum BlockToken{
			BLOCK_START,	BLOCK_HEADER,	BLOCK_HEADER_BELOW,		BLOCK_END,
};

enum BlockBorderType{
			BEGIN_BORDERS,						DASH_BORDERS, 			DASH_ASTERICKS,
			ASTERICK_BORDERS, 	    			ASTERICK_DASH,			DASH_DASH,
			UNKNOWN_BORDERS,					ASTERICK_ASTERICK,		NOT_BORDER,
};


#endif