######################################################################
##
## Filename: alu_32_tb.udo
## Created on: Thu Oct 20 9:53:46 AM Mountain Daylight Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
